### ISSUE TITLE
autoload.php missing?

### ISSUE THREAD

**Issue by modfiles** [ricardofiorani/duino-coin-php-miner#2]
Fatal error: Uncaught Error: Failed opening required '/code/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /code/miner.php:2

doesnt seem to exist in downloaded zip file or in any directory

**Comment by ricardofiorani** [comment]
@modfiles hey sorry, I didn't add the composer steps in the readme I guess.

If you are running it via docker you can run
```
$ docker run --rm --interactive --tty \
  --volume $PWD:/app \
  composer install
```

then

```
$ docker-compose up
```

and you should have your miner working.
Otherwise if you are running with PHP 8 locally, you should install composer (https://getcomposer.org/download/) and then run
```
composer install
```
