### ISSUE TITLE
New problem please update

### ISSUE THREAD

**Issue by heroshima404** [ricardofiorani/duino-coin-php-miner#4]
New problem, its get stuck
![Screenshot_20210715-214635_Termux](https://user-images.githubusercontent.com/77319651/125842475-57ddbda2-c32d-4027-bdb7-e185df9fb620.jpg)

**Comment by heroshima404** [comment]
Please update

**Comment by heroshima404** [comment]
Please update sir

**Comment by ricardofiorani** [comment]
Please see #8
