### ISSUE TITLE
Socket closed

### ISSUE THREAD

**Issue by JulienDev** [ricardofiorani/duino-coin-php-miner#5]
Hello,
Thank you @ricardofiorani  for your awesome project. I have an issue with your script, after few seconds I get a "socket closed" error, then it reconnects, receives a new work, and the socket is closing again. I'm stuck in this weird loop.

- [2021-08-07T11:58:44.602004+00:00] name.INFO: Connected to server version: 2.6 [] []
- [2021-08-07T11:58:44.623332+00:00] name.INFO: SERVER SENT DATA ["d647a041bd22b7a9926b5139c546a903977f23ce,29a5cc6bc71655e134a076318a72258964bbee3e,75000\n"] []
- [2021-08-07T11:58:44.623480+00:00] name.INFO: Starting to work {"baseHash":"d647a041bd22b7a9926b5139c546a903977f23ce","digest":"29a5cc6bc71655e134a076318a72258964bbee3e","difficulty":"75000\n"} []
- [2021-08-07T11:58:49.262216+00:00] name.DEBUG: Time difference [4.638556003570557] []
- [2021-08-07T11:58:49.262479+00:00] name.INFO: FOUND! {"result":4060325} []
- [2021-08-07T11:58:49.262591+00:00] name.INFO: Current HashRate {"hashRate":"8.75 Gh/s"} []
- [2021-08-07T11:58:49.284931+00:00] name.INFO: SERVER SENT DATA ["You have been moved to a higher difficulty tier\n"] []
- [2021-08-07T11:58:49.285086+00:00] name.INFO: Connected to server version: 0 [] []
- [2021-08-07T11:59:04.285648+00:00] name.WARNING: [SOCKET CLOSED] [] []
- [2021-08-07T11:59:04.285866+00:00] name.ALERT: Sleeping 10 seconds before trying again... [] []
- [2021-08-07T11:59:05.290359+00:00] name.INFO: 10 seconds before trying again. [] []
- [2021-08-07T11:59:06.292969+00:00] name.INFO: 9 seconds before trying again. [] []
- [2021-08-07T11:59:07.294461+00:00] name.INFO: 8 seconds before trying again. [] []
- [2021-08-07T11:59:08.297331+00:00] name.INFO: 7 seconds before trying again. [] []
- [2021-08-07T11:59:09.301297+00:00] name.INFO: 6 seconds before trying again. [] []
- [2021-08-07T11:59:10.302880+00:00] name.INFO: 5 seconds before trying again. [] []
- [2021-08-07T11:59:11.303665+00:00] name.INFO: 4 seconds before trying again. [] []
- [2021-08-07T11:59:12.305571+00:00] name.INFO: 3 seconds before trying again. [] []
- [2021-08-07T11:59:13.310144+00:00] name.INFO: 2 seconds before trying again. [] []
- [2021-08-07T11:59:14.313803+00:00] name.INFO: 1 seconds before trying again. [] []
- [2021-08-07T11:59:15.316519+00:00] name.INFO: 0 seconds before trying again. [] []
- [2021-08-07T11:59:15.316621+00:00] name.ALERT: Connecting to 51.15.127.80:2811... [] []
- [2021-08-07T11:59:15.343641+00:00] name.INFO: Asking server for a new job... [] []
- [2021-08-07T11:59:15.366198+00:00] name.INFO: SERVER SENT DATA ["2.6"] []
- [2021-08-07T11:59:15.366367+00:00] name.INFO: Connected to server version: 2.6 [] []
- [2021-08-07T11:59:15.387372+00:00] name.INFO: SERVER SENT DATA ["a1c86617a9c1618600fd4d9a3d3e8504664d5d84,26b244d8e0c60a416fa49e98bc9f733d30e2cc68,75000\n"] []

Do you know what's wrong and how I could fix it?

Thanks

**Comment by ricardofiorani** [comment]
Please see #8
