### ISSUE TITLE
Failed to open stream

### ISSUE THREAD

**Issue by z7737546436** [ricardofiorani/duino-coin-php-miner#6]
$ php miner.php
PHP Warning:  require(/home/pi/duino-coin-php-miner-main/vendor/autoload.php): Failed to open stream: No such file or directory in /home/pi/duino-coin-php-miner-main/miner.php on line 2
PHP Fatal error:  Uncaught Error: Failed opening required '/home/pi/duino-coin-php-miner-main/vendor/autoload.php' (include_path='.:/usr/share/php') in /home/pi/duino-coin-php-miner-main/miner.php:2
Stack trace:
#0 {main}
  thrown in /home/pi/duino-coin-php-miner-main/miner.php on line 2

Envirnment: PHP8

**Comment by ricardofiorani** [comment]
Please see #8
